# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4a205r2azdQsGLGNgYvYMThNud3cExP
"""

alphabet = 'abcdefghijklmnopqrstuvwxyz'

key = -5
newMessage = ''

message = input('Please enter a message:')

for character in message:
    if character in alphabet:
        position = alphabet.find(character)
        newPosition = (position + key) % 26
        newCharacter = alphabet[newPosition]
        newMessage += newCharacter
    else:
        newMessage += character  # This handles spaces and any other non-alphabet characters

print('Your new message is', newMessage)

alphabet = 'abcdefghijklmnopqrstuvwxyz'

key = -5
newMessage = ''

message = input('Please enter the encrypted message:')

for character in message:
    if character in alphabet:
        position = alphabet.find(character)
        newPosition = (position - key) % 26
        newCharacter = alphabet[newPosition]
        newMessage += newCharacter
    else:
        newMessage += character  # This handles spaces and any other non-alphabet characters

print('Your decrypted message is', newMessage)