# -*- coding: utf-8 -*-
"""Message Inverter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12PdNGhlEScsnBy5ciNKuCK4rJNjpENCp
"""

def invert_message(message):
    words = message.split(' ')
    inverted_words = [word[::-1] for word in words]
    inverted_message = ' '.join(inverted_words)
    return inverted_message

message = input('Please enter a message: ')
inverted_message = invert_message(message)
print('Your inverted message is:', inverted_message)

def revert_inverted_message(inverted_message):
    words = inverted_message.split(' ')
    original_words = [word[::-1] for word in words]
    original_message = ' '.join(original_words)
    return original_message

inverted_message = input('Please enter the inverted message: ')
original_message = revert_inverted_message(inverted_message)
print('Your original message is:', original_message)